name: 'Config YML Validation Action'
description: 'An action that validates config yml sections data'
author: 'Heber Silva'
branding:
  icon: file
  color: purple
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pokemon_id}}
