name: 'Config YML Validation Action'
description: 'An action that validates config yml sections data'
author: 'Heber Silva'
branding:
  icon: file
  color: purple
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pokemon_id}}
# inputs:
#   token:
#     description: >
#       GitHub token for GitHub API requests.
#       Users shouldn't need to set this themselves.
#     required: true
#     default: ${{ github.token }}
#   format:
#     description: >
#       Format of the steps output context.
#       Can be 'space-delimited', 'csv', or 'json'.
#     required: true
#     default: space-delimited
# outputs:
#   all:
#     description: >
#       Array of all changed files.
#   added:
#     description: >
#       Array of added files.
#   modified:
#     description: >
#       Array of modified files.
#   removed:
#     description: >
#       Array of removed files.
#   renamed:
#     description: >
#       Array of renamed files.
#   added_modified:
#     description: >
#       Array of all added and modified files.
#   # For backwards-compatibility
#   deleted:
#     description: >
#       Array of deleted files.
