name: 'Config YML Validation Action'
description: 'An action that validates config yml sections data'
author: 'Heber Silva'
branding:
  icon: file
  color: purple
inputs: 
  github_token:
    description: GitHub token secret
    required: true
  github_sha:
    description: GitHub sha
    required: true
outputs:
  pr_url:
    description: 'Pull request URL'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.github_sha }}
