name: Test

on:
  pull_request:
      types: [ opened, reopened, synchronize ]

jobs:
  debug:
    runs-on: ubuntu-latest
    name: Debug
    steps:
      - name: Print environment variables
        run: env

      - name: Print events.json
        run: cat "$GITHUB_EVENT_PATH"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: files
        name: Run the action
        uses: ./
        env: 
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_EVENT_PR_NUMER: ${{ github.event.pull_request.number }}

      # - name: Print steps context output
      #   run: |
      #     echo 'steps.files.outputs.all=${{ steps.files.outputs.all }}'
      #     echo 'steps.files.outputs.added=${{ steps.files.outputs.added }}'
      #     echo 'steps.files.outputs.modified=${{ steps.files.outputs.modified }}'
      #     echo 'steps.files.outputs.removed=${{ steps.files.outputs.removed }}'
      #     echo 'steps.files.outputs.renamed=${{ steps.files.outputs.renamed }}'
      #     echo 'steps.files.outputs.added_modified=${{ steps.files.outputs.added_modified }}'
      # - name: Get source
      #   uses: actions/checkout@v1
      # - name: Validate consul YML config
      #   uses: ./actions/config_validator
      #   id: pokemon1
      #   with:
      #     pokemon_id: 150
      # - name: Consul updates
      #   uses: ./actions/consul_updates
      #   id: pokemon2
      #   with:
      #     pokemon_id: 150
      # - name: Merge master
      #   uses: ./actions/merge_master
      #   id: pokemon4
      #   with:
      #     pokemon_id: 150
      # - name: Get the pokemon
      #   run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"